name: Django CI/CD with Docker Hub & DigitalOcean Kubernetes
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test

  build-and-deploy:
    name: Build and Deploy to DigitalOcean Kubernetes
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname -s)-$(uname -m) -o doctl
          chmod +x doctl
          sudo mv doctl /usr/local/bin
      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token ${{ secrets.DO_API_TOKEN }}
      - name: Retrieve Kubernetes Config
        run: doctl kubernetes cluster kubeconfig save k8stest-cluster

      - name: Deploy to Kubernetes
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
        run: |
          kubectl set image deployment/django-app django-app=$IMAGE_NAME --namespace=default
          kubectl rollout status deployment/django-app --namespace=default
