name: Django CI/CD with Docker Hub & DigitalOcean Kubernetes
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
  
  build-and-deploy:
    name: Build and Deploy to DigitalOcean Kubernetes
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Install and Configure DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.95.0/doctl-1.95.0-$(uname -s)-$(uname -m).tar.gz | tar xzv
          sudo mv doctl /usr/local/bin
          doctl auth init --access-token ${{ secrets.DO_API_TOKEN }}
      
      - name: Deploy to Kubernetes
        run: |
          doctl kubernetes cluster kubeconfig save k8stest-cluster
          kubectl set image deployment/django-app django-app=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }} --namespace=default
          kubectl rollout status deployment/django-app --namespace=default
