name: Django CI/CD Pipeline
on:
  push:
    branches:
      - main  # Triggers deployment on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Step 2: Set up Docker Buildx for advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # Use current directory as build context
          push: true  # Push image to registry
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
      
      # Step 5: Set up kubectl for Kubernetes interactions
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      # Step 6: Install and Configure DigitalOcean CLI
      - name: Install DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.95.0/doctl-1.95.0-$(uname -s)-$(uname -m).tar.gz | tar xzv
          sudo mv doctl /usr/local/bin
      
      # Step 7: Authenticate with DigitalOcean
      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token ${{ secrets.DO_API_TOKEN }}
      
      # Step 8: Retrieve Kubernetes Cluster Configuration
      - name: Get Kubernetes Config
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_NAME }}
      
      # Step 9: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          # Update deployment image
          kubectl set image deployment/django-app django-app=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }} --namespace=default
          
          # Verify rollout status
          kubectl rollout status deployment/django-app --namespace=default
